"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[\$]($style)'

[hostname]
format = '[@](white bold)[$hostname]($style) '
ssh_only = false

[username]
show_always = true
format = '[$user]($style)'

[directory]
truncation_length = 0
truncate_to_repo = false
