[general]
# import = ["~/.config/alacritty/themes/themes/gnome_terminal.toml"]

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
size = 11

[window]
dimensions.columns = 156
dimensions.lines = 32
padding.x = 12
padding.y = 12
opacity = 0.98
decorations = "full"
dynamic_title = true

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[env]
TERM = "xterm-256color"
